webtalk_init -webtalk_dir C:/Users/sarab/Desktop/Task3CAProject - Copy/final_ca_project_hehe.sim/sim_1/behav/xsim/xsim.dir/tb_toppppp_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Apr 27 21:01:00 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0938b055-f2d0-420b-bec1-a5f80a739fc4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "39153d9b9ddd4095bf862398446a4da9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "210" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2803 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "6400 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8308_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1674409250 -regid "" -xml C:/Users/sarab/Desktop/Task3CAProject - Copy/final_ca_project_hehe.sim/sim_1/behav/xsim/xsim.dir/tb_toppppp_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/sarab/Desktop/Task3CAProject - Copy/final_ca_project_hehe.sim/sim_1/behav/xsim/xsim.dir/tb_toppppp_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/sarab/Desktop/Task3CAProject - Copy/final_ca_project_hehe.sim/sim_1/behav/xsim/xsim.dir/tb_toppppp_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
